191025-웹팀스터디 깃헙스타랭킹 만들기
mash-up-kr-web/github_star pull request #4
Opened 2019-10-24 17:26 UTC by jo-bata

# Gitstar Ranking

## 무엇을 구현했나요?

- 함수형 컴포넌트 사용
- react hooks 맛보기

## 리뷰어가 어디서부터 보면 되나요?
- src/App.js

## 이 PR에 대한 나의 기분은?
- react와 아주 아주 조금 친해진 것 같다?
- react와 더 친해지고 싶다.

## 앞으로 도전할 과제는?
- 모듈화하기
- 스타 sorting하기
- 디자인 입히기

2019-10-24 17:28 UTC, jo-bata commented
권한이 없는지 upstream으로 push가 안되네요... 그래서 그런지 리뷰어도 추가가 안되어서 못했어요!

2019-10-25 02:39 UTC, chayeoi requested changes

2019-10-25 02:39 UTC, chayeoi commented on src/App.js
> +);
지금처럼 `renderHeaderForm`을 `App` 컴포넌트의 함수 몸체 안에 선언하지 않고 밖으로 분리하는 방식이라면,
그냥 `HeaderForm`으로 이름 짓고 73행에서도 함수를 호출하는 대신 `<HeaderForm inputValue={inputValue} onChangeInputValue={onChangeInputValue} getUserRepops={getUserRepos />`로 작성해도 괜찮습니다~
단, 이 컴포넌트를 함수 몸체 내부에 선언할 경우는 반드시 지금처럼 해주셔야 해요~ 😄

2019-10-25 02:39 UTC, chayeoi commented on src/App.js
> +      <div>{{ [STATE.INIT]: initialForm(), [STATE.SUCCESS]: successForm(), [STATE.FAIL]: failForm()}[appState]}</div>
`&&` 연산자로 컨디션을 걸어서 엘리먼트가 필요한 경우에만 생성되도록 해주면 성능적으로 더 좋습니다~

```
<div>{{
  [STATE.INIT]: appState === STATE.INIT && initialForm(),
  [STATE.SUCCESS]: appState === STATE.SUCCESS && successForm(),
  [STATE.FAIL]: appState === STATE.FAIL && failForm(),
}[appState]}</div>
```

2019-10-25 02:59 UTC, jo-bata commented on src/App.js
> +);
함수를 호출하는게 `React.createElement`로 마운트 되지 않아서 성능적으로 좀 더 빠르다고 판단하여 이렇게 작성했습니다!
몸체 내부 선언은 반드시 함수를 호출하여야 하는군요!
피드백 감사합니다! 🙏

2019-10-25 03:02 UTC, jo-bata commented on src/App.js
> +      <div>{{ [STATE.INIT]: initialForm(), [STATE.SUCCESS]: successForm(), [STATE.FAIL]: failForm()}[appState]}</div>
이런 세심한 부분을 놓쳤네요 역시 갓찬연...👍감사합니다 ㅎㅎ

2019-12-05 02:57 UTC, closed without merging