Feature/minsu
mash-up-kr-web/github_star pull request #5
Opened 2019-10-25 04:34 UTC by whitewolf23

# Gitstar Ranking

## 무엇을 구현했나요?
* class component와 3개의 함수형 컴포넌트로 프로젝트 구성
* bootstrap 을 통한 간단한 디자인
* instant search 

## 리뷰어가 어디서부터 보면 되나요?
* src/App.js

## 이 PR에 대한 나의 기분은?
* 이전에 경험을 너무 과신한 나머지 개발시간이 상당히 오래걸림 -> 반성
* 간단한 기초를 먼저 구현하고, 구조화 및 Redux 기능을 붙이는 게 낫다는 다시 한번 깨우침

## 앞으로 도전할 과제는?
* 모듈화하기
* 스타 sorting하기
* Redux, Redux-pender, immutable.js 를 이용한 Container.js를 만들어 state 관리해보기

2019-10-25 10:34 UTC, jo-bata requested changes
아유 제가 많이 부족하지만 민수님 코드 리뷰 한번 해보았습니다!

2019-10-25 10:34 UTC, jo-bata commented on src/Repo.js
> +              Stars: {repo.watchers_count}
`repo.watchers_count`니까 `Stars`를 `Watchers`로 수정하면 더 좋을 것 같아요!

2019-10-25 10:34 UTC, jo-bata commented on src/Repo.js
> +            <span className="badge badge-primary">
13~21행 까지 span 들이 className과 contents만 변경되니 이부분을 따로 함수로 작성해서 중복을 조금이나마 줄일 수 있을 것 같아요!

2019-10-25 10:34 UTC, jo-bata commented on src/Profile.js
> +  console.log(user)
user 값이 잘 들어오는지 확인하려고 찍은 console인 것 같습니다.
사소하지만 이부분은 push 하실때는 빼는게 더 좋은 것 같아요!

2019-10-25 10:34 UTC, jo-bata commented on src/Profile.js
> +          {/* <div className="col-md-4"> */}
8행과 34행의 주석처리 부분도 현재 불필요한 것 같아요!

2019-10-25 10:34 UTC, jo-bata commented on src/Profile.js
> +            <div className="card" style={{witdt : "18rem"}}>
`witdt` 혹시 `width` 오타난 것 같은데 맞나요?!

2019-10-25 10:34 UTC, jo-bata commented on src/Profile.js
> +              <li className="list-group-item">
12~25행 까지 반복되는 li 들이 className과 contents만 변경되니 이부분을 따로 함수로 작성해서 중복을 조금이나마 줄일 수 있을 것 같아요!

2019-10-25 10:34 UTC, jo-bata commented on src/Navbar.js
> +const Navbar = () => {
```js
const Navbar = () => (
  <nav className="navbar navbar-dark bg-info mb-3">
    <div className="container">
      <a href="#" className="navbar-brand">
       Github Star
      </a>
    </div>
  </nav>
);
```
이렇게 return 키워드를 생략할 수도 있을 것 같아요!

2019-10-25 10:34 UTC, jo-bata commented on src/App.js
> +  renderProfile = () => {
```js
renderProfile = ({ user, repos }) => (
    <div className="row">
      <div className="col-md-4">
        <Profile user={user} />
      </div>
      <div className="col-md-8">
        {
          repos.map((repo) => (
            <Repo key={repo.name} repo={repo} />
          ))
        }
      </div>
    </div>
  )
```
77행에서 `renderProfile` 함수 호출할때 파라미터로 `this.state`를 넘겨주고 return 구문들은 생략하는 것도 나쁘지 않아 보여요!

2019-10-27 05:09 UTC, chayeoi requested changes

2019-10-27 05:09 UTC, chayeoi commented on .env
> +NODE_PATH = src
정확한 이유는 저도 좀 더 알아봐야겠지만, `NODE_PATH`로 절대 경로 import를 설정하는 방식은 더 이상 [공식적으로 권장하는 방식은 아닌 듯 합니다~](https://github.com/facebook/create-react-app/issues/2338#issuecomment-303679710)

그 대신 문서에서는 [`jsconfig.json`을 통해 절대 경로를 설정하는 방법](https://create-react-app.dev/docs/importing-a-component/#absolute-imports)을 안내하고 있는데 이 방식을 적용해보시는 건 어떠신가요?😄

2019-10-27 05:09 UTC, chayeoi commented on src/App.js
> +    super();
지금은 `App` 컴포넌트가 따로 전달받는 prop이 없어서 괜찮겠지만, 혹시 모를 실수를 방지하기 위해 `super()`를 호출할 때 `constructor`가 받는 `props` 매개변수를 `super`에 넘겨주면 더 좋을 것 같습니다~ 😸

2019-10-27 05:09 UTC, chayeoi commented on src/App.js
> +        client_id : "2198861e66aa854efd6935e20a368d1999884bc8",
클라이언트 ID 같은 값은 `GITHUB_CLIENT_ID`와 같이 별도의 상수로 분리해서 관리하면 유지보수하기 더 수월할 것 같습니다~ 😃
그리고 `url`이나 `client_id`는 앱에서 시간이 지남에 따라 변경되는 값이 아니기 때문에 state로 관리하지 않아도 될 듯합니다~ React 문서에서는 [state로 관리해야 하는 대상](https://reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state)에 대해 다음과 같이 설명하고 있습니다. 

> Is it passed in from a parent via props? If so, it probably isn’t state.
Does it remain unchanged over time? If so, it probably isn’t state.
Can you compute it based on any other state or props in your component? If so, it isn’t state.

2019-10-27 05:09 UTC, chayeoi commented on src/App.js
> +    })
비동기적으로 수행되는 두 개의 작업 간에 순서가 보장될 필요가 없다면 `Promise.all`을 사용하여 `this.setState`를 한 번만 호출하도록 해서 리렌더링 횟수를 줄이는 게 좋을 듯합니다!

```javascript
// 방법 1
getUser = (e) => {
  // ...

  Promise.all(
    axios.get(`${url}/${user}?client_id=${client_id}`),
    axios.get(`${url}/${user}/repos?per_page=${count}&sort=${sort}&client_id=${client_id}`),
  )
    .then(({ data: user }, { data: repos }) => {
      this.setState({ user, repos })
    })

  this.setState({ user, repos })
}

// 방법 2
getUser = async (e) => {
  // ...

  const [{ data: user }, { data: repos }] = await Promise.all(
    axios.get(`${url}/${user}?client_id=${client_id}`),
    axios.get(`${url}/${user}/repos?per_page=${count}&sort=${sort}&client_id=${client_id}`),
  )

  this.setState({ user, repos })
}
```

2019-10-27 05:09 UTC, chayeoi commented on src/App.js
> +          {user.length !== 0 ? this.renderProfile(): null}
`0`은 Boolean 컨텍스트에서 `false`로 평가되는 falsy value이기 때문에, `user.length ? this.renderProfile() : null`과 같이 작성해도 좋을 것 같아요~ 😄
단, `render` 함수가 반환히는 값에 `0`을 제외한 falsy value는 렌더링되지 않지만 [`0`은 렌더링 결과에 포함]({ data: user }, { data: repos })되기 때문에 삼항 연산자를 사용한 점은 좋은 것 같습니다! 👍

2019-10-27 05:09 UTC, chayeoi commented on src/Profile.js
> +              <img className="card-img-top" src={user.avatar_url} />
[`ul`의 자식 요소로 사용 가능한 유일한 요소는 `li`](https://www.w3.org/TR/html51/grouping-content.html#the-ul-element)이기 때문에 `img` 요소가 DOM 트리에 정상적으로 포함되지 않을 것으로 예상됩니다~ `img`를 `ul` 요소 외부로 빼는게 좋을 것 같아요!

2019-10-27 05:50 UTC, whitewolf23 commented
현우님 감사합니다 !!! 곧 수정하겠습니다

2019년 10월 25일 (금) 오후 7:35, Hyeonwoo Cho <notifications@github.com>님이 작성:

> *@jo-bata* requested changes on this pull request.
>
> 아유 제가 많이 부족하지만 민수님 코드 리뷰 한번 해보았습니다!
> ------------------------------
>
> In src/Repo.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338980911>
> :
>
> > +
>
> +const Repo = ({repo}) => {
>
> +  return (
>
> +    <div className="card card-body mb-2">
>
> +        <div className="row">
>
> +          <div className="col-md-6">
>
> +            <a href={repo.html_url} target="_blank">
>
> +              {repo.name}
>
> +            </a>
>
> +          </div>
>
> +          <div className="col-md-6">
>
> +            <span className="badge badge-primary">
>
> +              Stars: {repo.stargazers_count}
>
> +            </span>
>
> +            <span className="badge badge-secondary">
>
> +              Stars: {repo.watchers_count}
>
>
> repo.watchers_count니까 Stars를 Watchers로 수정하면 더 좋을 것 같아요!
> ------------------------------
>
> In src/Repo.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338983281>
> :
>
> > @@ -0,0 +1,28 @@
>
> +import React from 'react'
>
> +
>
> +const Repo = ({repo}) => {
>
> +  return (
>
> +    <div className="card card-body mb-2">
>
> +        <div className="row">
>
> +          <div className="col-md-6">
>
> +            <a href={repo.html_url} target="_blank">
>
> +              {repo.name}
>
> +            </a>
>
> +          </div>
>
> +          <div className="col-md-6">
>
> +            <span className="badge badge-primary">
>
>
> 13~21행 까지 span 들이 className과 contents만 변경되니 이부분을 따로 함수로 작성해서 중복을 조금이나마 줄일
> 수 있을 것 같아요!
> ------------------------------
>
> In src/Profile.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338983825>
> :
>
> > @@ -0,0 +1,40 @@
>
> +import React from 'react';
>
> +
>
> +const Profile = ({user}) => {
>
> +  console.log(user)
>
>
> user 값이 잘 들어오는지 확인하려고 찍은 console인 것 같습니다.
> 사소하지만 이부분은 push 하실때는 빼는게 더 좋은 것 같아요!
> ------------------------------
>
> In src/Profile.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338984093>
> :
>
> > @@ -0,0 +1,40 @@
>
> +import React from 'react';
>
> +
>
> +const Profile = ({user}) => {
>
> +  console.log(user)
>
> +  return (
>
> +    <div>
>
> +        <div className="row">
>
> +          {/* <div className="col-md-4"> */}
>
>
> 8행과 34행의 주석처리 부분도 현재 불필요한 것 같아요!
> ------------------------------
>
> In src/Profile.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338984376>
> :
>
> > @@ -0,0 +1,40 @@
>
> +import React from 'react';
>
> +
>
> +const Profile = ({user}) => {
>
> +  console.log(user)
>
> +  return (
>
> +    <div>
>
> +        <div className="row">
>
> +          {/* <div className="col-md-4"> */}
>
> +            <div className="card" style={{witdt : "18rem"}}>
>
>
> witdt 혹시 width 오타난 것 같은데 맞나요?!
> ------------------------------
>
> In src/Profile.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338985578>
> :
>
> > @@ -0,0 +1,40 @@
>
> +import React from 'react';
>
> +
>
> +const Profile = ({user}) => {
>
> +  console.log(user)
>
> +  return (
>
> +    <div>
>
> +        <div className="row">
>
> +          {/* <div className="col-md-4"> */}
>
> +            <div className="card" style={{witdt : "18rem"}}>
>
> +            <ul className="list-group list-group-flush">
>
> +              <img className="card-img-top" src={user.avatar_url} />
>
> +              <li className="list-group-item">
>
>
> 12~25행 까지 반복되는 li 들이 className과 contents만 변경되니 이부분을 따로 함수로 작성해서 중복을 조금이나마
> 줄일 수 있을 것 같아요!
> ------------------------------
>
> In src/Navbar.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338986572>
> :
>
> > @@ -0,0 +1,15 @@
>
> +import React from 'react';
>
> +
>
> +const Navbar = () => {
>
>
> const Navbar = () => (
>
>   <nav className="navbar navbar-dark bg-info mb-3">
>
>     <div className="container">
>
>       <a href="#" className="navbar-brand">
>
>        Github Star
>
>       </a>
>
>     </div>
>
>   </nav>
>
> );
>
> 이렇게 return 키워드를 생략할 수도 있을 것 같아요!
> ------------------------------
>
> In src/App.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r338988858>
> :
>
> > +    .then(({data} ) => {
>
> +      this.setState({
>
> +        user: data
>
> +      })
>
> +    })
>
> +
>
> +    axios.get(
>
> +      `${url}/${user}/repos?per_page=${count}&sort=${sort}&client_id=${client_id}`
>
> +    )
>
> +    .then(({data} ) => {
>
> +      this.setState({
>
> +        repos: data
>
> +      })
>
> +    })
>
> +  }
>
> +  renderProfile = () => {
>
>
> renderProfile = ({ user, repos }) => (
>
>     <div className="row">
>
>       <div className="col-md-4">
>
>         <Profile user={user} />
>
>       </div>
>
>       <div className="col-md-8">
>
>         {
>
>           repos.map((repo) => (
>
>             <Repo key={repo.name} repo={repo} />
>
>           ))
>
>         }
>
>       </div>
>
>     </div>
>
>   )
>
> 77행에서 renderProfile 함수 호출할때 파라미터로 this.state를 넘겨주고 return 구문들은 생략하는 것도
> 나쁘지 않아 보여요!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mash-up-kr-web/github_star/pull/5?email_source=notifications&email_token=AETCKLFU5ZBGH4UNT24ILJTQQLDVHA5CNFSM4JE6NHE2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCJHBOEQ#pullrequestreview-307107602>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETCKLGKVY7QDE7SXDSGSKTQQLDVHANCNFSM4JE6NHEQ>
> .
>

2019-10-27 05:51 UTC, whitewolf23 commented
감사합니다 찬연님!! 바로 수정할게여!!


2019년 10월 27일 (일) 오후 2:09, Chanyeon Kim <notifications@github.com>님이 작성:

> *@chayeoi* requested changes on this pull request.
> ------------------------------
>
> In .env
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r339323439>
> :
>
> > @@ -0,0 +1,2 @@
>
> +NODE_PATH = src
>
>
> 정확한 이유는 저도 좀 더 알아봐야겠지만, NODE_PATH로 절대 경로 import를 설정하는 방식은 공식적으로 권장하는 방식은
> 아니라고 합니다~
> <https://github.com/facebook/create-react-app/issues/2338#issuecomment-303679710>
>
> 그 대신 문서에서는 jsconfig.json을 통해 절대 경로를 설정하는 방법
> <https://create-react-app.dev/docs/importing-a-component/#absolute-imports>을
> 안내하고 있는데 이 방식을 적용해보시는 건 어떠신가요?😄
> ------------------------------
>
> In src/App.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r339323516>
> :
>
> > @@ -0,0 +1,84 @@
>
> +import React, { Component } from 'react';
>
> +import Navbar from 'Navbar';
>
> +import axios from 'axios';
>
> +import Profile from 'Profile';
>
> +import Repo from 'Repo';
>
> +class App extends Component {
>
> +  constructor(){
>
> +    super();
>
>
> 지금은 App 컴포넌트가 따로 전달받는 prop이 없어서 괜찮겠지만, 혹시 모를 실수를 방지하기 위해 super()를 호출할 때
> constructor가 받는 props 매개변수를 super에 넘겨주면 더 좋을 것 같습니다~ 😸
> ------------------------------
>
> In src/App.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r339323536>
> :
>
> > @@ -0,0 +1,84 @@
>
> +import React, { Component } from 'react';
>
> +import Navbar from 'Navbar';
>
> +import axios from 'axios';
>
> +import Profile from 'Profile';
>
> +import Repo from 'Repo';
>
> +class App extends Component {
>
> +  constructor(){
>
> +    super();
>
> +    this.state = {
>
> +      github: {
>
> +        url: "https://api.github.com/users",
>
> +        client_id : "2198861e66aa854efd6935e20a368d1999884bc8",
>
>
> 클라이언트 ID 같은 값은 GITHUB_CLIENT_ID와 같이 별도의 상수로 분리해서 관리하면 유지보수하기 더 수월할 것
> 같습니다~ 😃
> 그리고 url이나 client_id는 앱에서 시간이 지남에 따라 변경되는 값이 아니기 때문에 state로 관리하지 않아도 될
> 듯합니다~ React 문서에서는 state로 관리해야 하는 대상
> <https://reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state>에
> 대해 다음과 같이 설명하고 있습니다.
>
> Is it passed in from a parent via props? If so, it probably isn’t state.
> Does it remain unchanged over time? If so, it probably isn’t state.
> Can you compute it based on any other state or props in your component? If
> so, it isn’t state.
>
> ------------------------------
>
> In src/App.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r339323830>
> :
>
> > +    axios.get(
>
> +      `${url}/${user}?client_id=${client_id}`
>
> +    )
>
> +    .then(({data} ) => {
>
> +      this.setState({
>
> +        user: data
>
> +      })
>
> +    })
>
> +
>
> +    axios.get(
>
> +      `${url}/${user}/repos?per_page=${count}&sort=${sort}&client_id=${client_id}`
>
> +    )
>
> +    .then(({data} ) => {
>
> +      this.setState({
>
> +        repos: data
>
> +      })
>
> +    })
>
>
> 비동기적으로 수행되는 두 개의 작업 간에 순서가 보장될 필요가 없다면 Promise.all을 사용하여 this.setState를 한
> 번만 호출하도록 해서 리렌더링 횟수를 줄이는 게 좋을 듯합니다!
>
> // 방법 1
> getUser = (e) => {
>
>   // ...
>
>
>
>   Promise.all(
>
>     axios.get(`${url}/${user}?client_id=${client_id}`),
>
>     axios.get(`${url}/${user}/repos?per_page=${count}&sort=${sort}&client_id=${client_id}`),
>
>   )
>
>     .then(({ data: user }, { data: repos }) => {
>
>       this.setState({ user, repos })
>
>     })
>
>
>
>   this.setState({ user, repos })
>
> }
>
>
> // 방법 2
>
> getUser = async (e) => {
>
>   // ...
>
>
>
>   const [{ data: user }, { data: repos }] = await Promise.all(
>
>     axios.get(`${url}/${user}?client_id=${client_id}`),
>
>     axios.get(`${url}/${user}/repos?per_page=${count}&sort=${sort}&client_id=${client_id}`),
>
>   )
>
>
>
>   this.setState({ user, repos })
>
> }
>
> ------------------------------
>
> In src/App.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r339323917>
> :
>
> > +  }
>
> +
>
> +  render() {
>
> +    const {user} = this.state;
>
> +    return (
>
> +      <div className="App">
>
> +        <Navbar />
>
> +        <div className="container">
>
> +          <div className="card card-body">
>
> +            <h1>GitStar Ranking</h1>
>
> +            <p className="lead">
>
> +              Unofficial GitHub star ranking for users, organizations and repositories.
>
> +            </p>
>
> +              <input onChange={this.getUser} id="search" type="text" className="form-control" required />
>
> +          </div>
>
> +          {user.length !== 0 ? this.renderProfile(): null}
>
>
> 0은 Boolean 컨텍스트에서 false로 평가되는 falsy value이기 때문에, user.length ?
> this.renderProfile() : null과 같이 작성해도 좋을 것 같아요~ 😄
> 단, render 함수가 반환히는 값에 0을 제외한 falsy value는 렌더링되지 않지만 [0은 렌더링 결과에 포함]({
> data: user }, { data: repos })되기 때문에 삼항 연산자를 사용한 점은 좋은 것 같습니다! 👍
> ------------------------------
>
> In src/Profile.js
> <https://github.com/mash-up-kr-web/github_star/pull/5#discussion_r339325313>
> :
>
> > @@ -0,0 +1,40 @@
>
> +import React from 'react';
>
> +
>
> +const Profile = ({user}) => {
>
> +  console.log(user)
>
> +  return (
>
> +    <div>
>
> +        <div className="row">
>
> +          {/* <div className="col-md-4"> */}
>
> +            <div className="card" style={{witdt : "18rem"}}>
>
> +            <ul className="list-group list-group-flush">
>
> +              <img className="card-img-top" src={user.avatar_url} />
>
>
> ul의 자식 요소로 사용 가능한 유일한 요소는 li
> <https://www.w3.org/TR/html51/grouping-content.html#the-ul-element>이기 때문에
> img 요소가 DOM 트리에 정상적으로 포함되지 않을 것으로 예상됩니다~ img를 ul 요소 외부로 빼는게 좋을 것 같아요!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mash-up-kr-web/github_star/pull/5?email_source=notifications&email_token=AETCKLGREXAKSH7XRJ767X3QQUPBTA5CNFSM4JE6NHE2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCJKOADI#pullrequestreview-307552269>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETCKLE6CWCRE6B7HNWTFGDQQUPBTANCNFSM4JE6NHEQ>
> .
>

2019-10-27 10:17 UTC, chayeoi requested changes

2019-10-27 10:17 UTC, chayeoi commented on src/App.js
> +    })
비동기 에러 핸들링 로직도 더해주시면 API 호출 수 제한이 걸렸을 때(403)나 일치하는 유저를 검색할 수 없는 경우(404)에 사용자에게 적절한 정보를 제공해줄 수 있을 것 같습니다~ 😄

2021-01-04 15:12 UTC, closed without merging