191027-웹팀스터디 깃헙스타랭킹 만들기
mash-up-kr-web/github_star pull request #6
Opened 2019-10-27 11:02 UTC by jieunjieun

# Gitstar Ranking
## 무엇을 구현했나요?
유저 정보 컴포넌트
레포지토리 정보 컴포넌트
유저 정보 부르는 api
레포 정보 부르는 api

## 리뷰어가 어디서부터 보면 되나요?
src/App.tsx
src/components

## 이 PR에 대한 나의 기분은?
1. 여기다 PR 날리는지 모르고 개인 깃헙에 날렸네요.. 어쩐지..
2. 간단한 프로젝트인데 너무나 오버스택인 것 같아서.. 괜히 이렇게 했나 싶기도 하네요

## 앞으로 도전할 과제는?
1. 유저 정보 없을 때 에러처리하는 로직을 넣고 싶어요.
2. 현재 요청, 성공, 실패를 액션으로 처리하고 있는데 실패 처리 액션을 사용해야합니다.(1번과 비슷한 내용)

2019-10-30 11:40 UTC, chayeoi requested changes

2019-10-30 11:40 UTC, chayeoi commented on src/App.tsx
> +  const [userName, setUsername] = useState('' as any);
사소한 부분이긴 하지만, `setUsername`에도 `userName`과 일관된 카멜케이스를 적용해서 `setUserName`으로 적으면 좋을 것 같습니다~ 😄

2019-10-30 11:40 UTC, chayeoi commented on src/App.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(App);
16행에서 `useDispatch`도 사용하는 걸로 확인됩니다. `useDispatch`와 `connect`에 `mapDispatchToProps`를 넘기는 방식 중 하나만 사용해도 될 것 같은데 이렇게 하신 이유가 있나요~? 😄

2019-10-30 11:40 UTC, chayeoi commented on src/App.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(App);
다시 확인해보니 `connect` 함수의 `mapDispatchToProps`로 컴포넌트에 내려준 `requestUserInfo`, `requestUserRepoInfo` prop은 사용되지 않는 걸로 보이네요. 지워도 될 것 같습니다~ `mapStateToProps`도 `useSelector`로 대체하면 `connect` 함수로 감싸는 수고를 덜 수 있을 것 같은데 어떠신가요~? 😸

2019-10-30 11:40 UTC, chayeoi commented on src/apis/github.ts
> +  return get(`/users/${userName}`).then(value => value);
`then` 절에서 인자로 들어온 값을 그대로 반환만 하고 있으므로 이 부분은 그냥 지워도 될 듯합니다~!
그리고 함수 몸체에 값을 반환하는 부분만 들어있으므로 `return` 키워드를 생략하고 쓰면 더 깔끔할 것 같아요~ 😋

2019-10-30 11:40 UTC, chayeoi commented on src/apis/github.ts
> +  return get(`/users/${userName}/repos`).then(value => value);
5행과 같은 의견입니다~

2019-10-30 11:40 UTC, chayeoi commented on src/apis/github.ts
> +import { get } from './index';
불러오는 경로가 `index.ts`라면 `.`만 써도 괜찮을 거 같습니다~

```javascript
import { get } from '.';
```

2019-10-30 11:40 UTC, chayeoi commented on src/apis/index.ts
> +  return axios.get(`${process.env.REACT_APP_DOMAIN}${url}`)
`axios` 객체에 디폴트 설정으로 `baseURL`을 한 번 설정하는 방법은 어떠신가요~? 😄 

> `baseURL` will be prepended to `url` unless `url` is absolute.
It can be convenient to set `baseURL` for an instance of axios to pass relative URLs
to methods of that instance. 

```javascript
axios.defaults.baseURL = process.env.REACT_APP_DOMAIN;

axios.get(`/users/${userName}/repos`);
```

axios 객체에 전역적으로 `baseURL`을 설정하는 방식이 찝찝하다면 커스텀 인스턴스를 만들어 사용해도 괜찮을 것 같습니다~
당연하게도 인스턴스 이름은 짓는 사람 자유지만, 저는 주로 `http` 요청을 위한 인스턴스에 대해서는 `http`라는 네이밍으로 사용하고 있는데요. [axios 라이브러리 자체가 Angular의 `$http` 클라이언트로부터 큰 영감을 받았다](https://github.com/axios/axios#credits)고 해서, 그에 따라 `http`라는 네이밍을 사용하고 있습니다 ㅎㅎ

```javascript
const http = axios.create({
  baseURL: process.env.REACT_APP_DOMAIN,
});

http.get(`/users/${userName}/repos`);
```

2019-10-30 11:40 UTC, chayeoi commented on src/components/Container/Repository.tsx
> +export const Repository = (props: any) => {
`App` 컴포넌트에는 default export를 사용하고, 다른 컴포넌트들에 대해서는 named export 방식을 사용하시는 이유가 궁금합니다~ 😃

2019-10-30 11:40 UTC, chayeoi commented on src/components/Container/Repository.tsx
> +              <tr key={key}>
서버로부터 응답받은 데이터 안에 각 레포지토리를 유일하게 구분할 수 있는 식별자 값이 있을 것으로 생각됩니다.
인덱스를 `key`로 사용하는 것보다 서버에서 받은 식별자(`id`)를 키로 사용하면 더 안전할 것 같습니다~ 😃

2019-10-30 11:40 UTC, chayeoi commented on src/index.tsx
> +      <App />
들여쓰기가 한 번 더 들어간 듯합니다~

2019-10-30 11:40 UTC, chayeoi commented on src/store/reducers/repo.ts
> +    draft.sortedData = sortBy(action.payload, ['stargazers_count', 'name']).reverse();
원본 데이터와 정렬된 데이터를 스토어에 각각 나누어 저장해야만 하는 이유가 있나요~?
스토어에는 원본 데이터만 저장하고, 데이터를 화면에 뿌려줄 때 원하는 순서로 정렬하도록 하면 메모리 사용을 줄일 수 있을 것 같습니다 😄

2019-10-30 11:40 UTC, chayeoi commented on src/store/reducers/repo.ts
> +      return total += value.stargazers_count;
반환값을 `total + value.stargazers_count`와 같이 써도 될 것 같고, lodash의 `sumBy`를 이용하면 좀 더 간단하게 작성할 수도 있습니다~

```javascript
sumBy(action.payload, repo => repo.stargazers_count);
```

2019-10-30 11:40 UTC, chayeoi commented on src/store/reducers/repo.ts
> +const _successUserRepoInfo = (action: any, draft: any) => {
함수 이름 앞에 사용하신 언더스코어(`_`) 기호가 어떤 의미인지 궁금합니다~!

2019-10-30 11:40 UTC, chayeoi commented on src/store/reducers/repo.ts
> +        return _successUserRepoInfo(action, draft);
`produce`에서 값을 반환하지 않아도 동작하는 데 이상 없을 것 같습니다~ 😄

2019-10-30 11:40 UTC, chayeoi commented on src/store/sagas/rootSaga.ts
> +    yield spawn(function* () {
와우 `spawn`이라는 것도 있군요,,! `spawn`이 어떤 작업을 위한 이펙트 생성자인지 설명해주실 수 있나여 ㅎㅎ?

2019-10-30 11:40 UTC, chayeoi commented on src/store/sagas/sagas.ts
> +}
이 단계에서 에러가 발생하면 `watchRequestUserInfo` 사가 함수로 에러가 전파되나요~?
만약 그렇지 않다면 이 곳에서 에러를 캐치하도록 하여 뷰 레이어에서 사용자에게 에러에 대한 정보를 보여주도록 하면 더 좋을 것 같습니다~ 😄

2019-10-31 09:13 UTC, jieunjieun commented on src/App.tsx
> +  const [userName, setUsername] = useState('' as any);
감사합니다!

2019-10-31 09:16 UTC, jieunjieun commented on src/App.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(App);
아 넵넵 저 당시에 hook을 사용할까 그냥 connect 사용해서 할까 갈팡질팡 하다가 제대로 코드 정리를 못한 것 같네요ㅠ
아직 useSelector, useDispatch 를 사용해보지 않아서 고민을 했었는데, 이번 기회에 한번 사용해볼게요! 감사합니다!

2021-01-04 15:12 UTC, closed without merging